
version: '3.8'
services:
  documentation:
    container_name: documentation
    image: wlcamargo/mkdocs
    ports:
      - "8005:8000"
    volumes:
      - ./:/docs
    stdin_open: true
    tty: true